### ISSUE TITLE
GNOME Keyring integration makes Firefox 43.0a2 freeze

### ISSUE THREAD

**Issue by antistress** [swick/mozilla-gnome-keyring#31] opened 2015-10-03 23:05 UTC
Hi,

I used to enjoy this add-on but recently I had to remove it since it makes Firefox freeze on newer versions.
I don't know if it's related to Firefox move to e10s ?
I'm using Firefox aurora from http://mozilla.debian.net/ on my Debian Sid 64 bits system
Thanks !

**Comment by swick** [comment] 2015-10-13 14:46
I can't reproduce the problem.

**Comment by rhertzog** [comment] 2015-10-20 09:35
@swick Can you try with GNOME Keyring 3.18.1 ? I have the same problem on Debian unstable.

And I filed it on gnome-keyring thinking it might be a regression of GNOME Keyring more than a regression of this extension: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=800660

**Comment by rhertzog** [comment] 2015-10-20 09:36
And I have the problem with iceweasel/firefox 38, so it's not really related to the browser version.

**Comment by rhertzog** [comment] 2015-10-20 09:39
What can be done to debug the problem? Is there a tool to watch the dbus requests that might get stuck? Maybe some timeout handling would be in order to avoid freezes?

**Comment by rhertzog** [comment] 2015-10-20 10:28
I have posted some dbus monitor calls in https://bugzilla.gnome.org/show_bug.cgi?id=756032 and I discovered that the problem goes away if you explicitly select the "login" keyring instead of keeping the default configuration of using the default keyring...

**Comment by rhertzog** [comment] 2015-10-20 14:06
And the discussion now continues in https://bugzilla.gnome.org/show_bug.cgi?id=756865 since it's a separate bug. I am more and more convinced that the issue is only in gnome-keyring and not in mozilla-gnome-keyring.

**Comment by swick** [comment] 2015-10-20 15:01
Thank you. I'll keep tabs on it.

**Comment by infinity0** [comment] 2015-10-21 10:44
Noting potential workaround here: https://bugzilla.gnome.org/show_bug.cgi?id=756032#c23 Other people should also try it and report back.

**Comment by mitya57** [comment] 2015-10-21 13:26
I have written a [patch for gnome-keyring] that should fix the issue. If someone tries it and tells me if it works, that would be nice.

[patch for gnome-keyring]: https://bugzilla.gnome.org/show_bug.cgi?id=756865#c5

**Comment by swick** [comment] 2016-09-24 03:16
Closing, because it seems to be fixed. Please comment if it's still a problem for you.

**Closed by swick** 2016-09-24 03:16 UTC
